update CI

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -62,6 +62,12 @@ jobs:
           name: code-coverage-report
           path: build/reports/jacoco/test/html/**
 
+      - name: Run SonarQube analysis
+         run: |
+          if ! gradle sonarqube; then
+            echo "SonarQube analysis failed or is not available. Skipping..."
+          fi
+
       # # 12. Log in to Docker Hub
       # - name: Log in to Docker Hub
       #   uses: docker/login-action@v2
@@ -91,7 +97,7 @@ jobs:
         run: docker logs hotel-booking-system-container > deployment.log
 
       - name: Upload deployment log
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: deployment-log
           path: deployment.log
