Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
-          java-version: 17
+          java-version: 8
           distribution: 'adopt'
 
       # 4. Build the JAR file using Gradle
@@ -29,7 +29,7 @@ jobs:
       - name: List build/libs directory
         run: ls -la build/libs
 
-      # 6. Copy text files to build/libs
+      # 6 Copy text files to build/libs
       - name: Copy text files
         run: ./gradlew copyResources 
 
@@ -62,37 +62,39 @@ jobs:
           name: code-coverage-report
           path: build/reports/jacoco/test/html/**
 
-      # 12. Log in to Docker Hub
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Run SonarQube analysis
+        run: |
+          if ! gradle sonarqube; then
+            echo "SonarQube analysis failed or is not available. Skipping..."
+          fi
+      # # 12. Log in to Docker Hub
+      # - name: Log in to Docker Hub
+      #   uses: docker/login-action@v2
+      #   with:
+      #     username: ${{ secrets.DOCKER_USERNAME }}
+      #     password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # 13. Extract metadata (tags, labels) for Docker
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v4
-        with:
-          images: ${{ secrets.DOCKER_USERNAME }}/hotelbookingsystem
+      # # 13. Extract metadata (tags, labels) for Docker
+      # - name: Extract metadata (tags, labels) for Docker
+      #   id: meta
+      #   uses: docker/metadata-action@v4
+      #   with:
+      #     images: ${{ secrets.DOCKER_USERNAME }}/hotelbookingsystem
 
       # 14. Build Docker image
       - name: Build Docker image
         uses: docker/build-push-action@v4
         with:
           context: .
-          push: true  # Set to true to push the image to Docker Hub
-          tags: ${{ secrets.DOCKER_USERNAME }}/hotelbookingsystem:latest
+          push: false
+          tags: hotel-booking-system
 
-      # 15. Run image with container
       - name: Run image with container
-        run: docker run -d --name hotel-booking-system-container ${{ secrets.DOCKER_USERNAME }}/hotelbookingsystem:latest
+        run: docker run -d --name hotel-booking-system-container hotel-booking-system
 
-      # 16. Generate deployment log
       - name: Generate deployment log
         run: docker logs hotel-booking-system-container > deployment.log
 
-      # 17. Upload deployment log
       - name: Upload deployment log
         uses: actions/upload-artifact@v4
         with:
